generic:
  name: 'bi_directional_LSTM'

train:
  model_dir: 'model/bi_model'
  steps: 10000
  batch_size: 32
  lr: 0.00002

model:
  is_bidirectional: Y
  is_attended: FALSE
  hidden_units: [128, 128]
  in_dropout: 1.0
  out_dropout: 1.0