generic:
  name: 'unidirectional_LSTM'

train:
  model_dir: 'model/simple_model'
  steps: 10000
  batch_size: 32
  lr: 0.00002

model:
  is_bidirectional: FALSE
  is_attended: FALSE
  hidden_units: [128, 128]
  in_dropout: 1.0
  out_dropout: 0.8